name: JR Recommender CI

on:
  push:
    branches: [ "dev/Aaron_ML_POC" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install lightgbm xgboost

      - name: Run full pipeline system test
        run: |
          python scripts/test_complete_pipeline.py --data data/raw/data_raw.csv
